# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd9b1485f9459235782ce52f5091f7f90bcbd27f96e1ab3b5322c289697906a17587f57e57f2d640910ddfb0985f515aba8c71454753eaa52b422ebd40da698c
  mail_user_name: admin@myexopets.ru
  mail_password: ZaQ123!@#
test:
  secret_key_base: 706cadd5d4e2a70b1791e7bba4cd38f87c78c7e6448ee174292ec7be88fb8e87fc9e9308438e9b32b91b8261c24eb664e995cc4f128d55e4420ac62a0b5d58e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
